### ISSUE TITLE
Chrome version too old (Mac)

### ISSUE THREAD

**Issue by nimshkedy** [gologinapp/gologin#104]
(venv) nimshkedy@Nimrods-MacBook-Pro pygologin % python gologin-selenium.py
executablePath /Users/nimshkedy/.gologin/browser/orbita-browser-112/Orbita-Browser.app/Contents/MacOS/Orbita
no proxy
[94070:259:0619/152738.526908:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.

DevTools listening on ws://127.0.0.1:3500/devtools/browser/87ef227b-0d4b-4975-8456-e454a4792b61
objc[94081]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x2428c1518) and /Users/nimshkedy/.gologin/browser/orbita-browser-112/Orbita-Browser.app/Contents/Frameworks/Orbita Framework.framework/Versions/112.0.5615.49/Libraries/libGLESv2.dylib (0x1058f3c58). One of the two will be used. Which one is undefined.
/Users/nimshkedy/PycharmProjects/Top100/pygologin/gologin-selenium.py:24: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=chrome_driver_path, options=chrome_options)
[94070:259:0619/152739.271256:ERROR:service_worker_task_queue.cc(232)] DidStartWorkerFail ibfmpbijpkkodbfphhfcpgapnakmlafo: 5
Traceback (most recent call last):
  File "/Users/nimshkedy/PycharmProjects/Top100/pygologin/gologin-selenium.py", line 24, in <module>
    driver = webdriver.Chrome(executable_path=chrome_driver_path, options=chrome_options)
  File "/Users/nimshkedy/PycharmProjects/Top100/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/Users/nimshkedy/PycharmProjects/Top100/venv/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/Users/nimshkedy/PycharmProjects/Top100/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/nimshkedy/PycharmProjects/Top100/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/nimshkedy/PycharmProjects/Top100/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/Users/nimshkedy/PycharmProjects/Top100/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:3500
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 112.0.5615.49
Stacktrace:
0   chromedriver                        0x00000001006bff48 chromedriver + 4226888
1   chromedriver                        0x00000001006b84f4 chromedriver + 4195572
2   chromedriver                        0x00000001002fcd68 chromedriver + 281960
3   chromedriver                        0x0000000100328bac chromedriver + 461740
4   chromedriver                        0x0000000100321d04 chromedriver + 433412
5   chromedriver                        0x000000010035f93c chromedriver + 686396
6   chromedriver                        0x000000010035f164 chromedriver + 684388
7   chromedriver                        0x000000010032bf1c chromedriver + 474908
8   chromedriver                        0x000000010032cef4 chromedriver + 478964
9   chromedriver                        0x000000010068159c chromedriver + 3970460
10  chromedriver                        0x00000001006856f0 chromedriver + 3987184
11  chromedriver                        0x000000010068b5b4 chromedriver + 4011444
12  chromedriver                        0x00000001006862fc chromedriver + 3990268
13  chromedriver                        0x000000010065e1c0 chromedriver + 3826112
14  chromedriver                        0x00000001006a2088 chromedriver + 4104328
15  chromedriver                        0x00000001006a21e0 chromedriver + 4104672
16  chromedriver                        0x00000001006b1f28 chromedriver + 4169512
17  libsystem_pthread.dylib             0x00000001a9f2206c _pthread_start + 148
18  libsystem_pthread.dylib             0x00000001a9f1ce2c thread_start + 8

(venv) nimshkedy@Nimrods-MacBook-Pro pygologin %

**Comment by javpascal** [comment]
+1

**Comment by igortikushEasync** [comment]
The issue is not related to the repo
