### ISSUE TITLE
Can't create/launch simple profile (Issue with zero_profile)

### ISSUE THREAD

**Issue by danbopes** [gologinapp/gologin#132]
```
import GoLogin from 'gologin';

const [_execPath, _filePath] = process.argv;

const GL = new GoLogin({
    skipOrbitaHashChecking: true,
    waitWebsocket: true,
    token: process.env.GOLOGIN_API_TOKEN
});

(async () => {

  const profile_id = await GL.create({
    name: 'profile_win',
    os: 'win', // 'win', 'lin', 'android'
    // isM1: true, // for Mac M1
    navigator: {
      language: 'en-US,en;q=0.9',
      userAgent: 'random', // get random user agent for selected os
      resolution: '1024x768',
    },
    proxyEnabled: false,
    proxy: {
      mode: 'none',
    },
  });

  console.log('profile id=', profile_id);

  await GL.setProfileId(profile_id);

  const wsUrl = await GL.startLocal();

  console.log(wsUrl);
})()
```

I'm getting the following error when attempting to launch this profile:

> Error: ENOENT: no such file or directory, open '/tmp/gologin_profile_6642e4c45834d62b92b54b58/Default/Preferences'

```
  gologin getProfileS3 token= [snipped] profile= 6642e4c45834d62b92b54b58 s3path= zero_profile.zip +3ms
  gologin loading profile from public s3 bucket, url= https://files-gateway.gologin.com/download +1ms
  gologin FILE READY /tmp/gologin_6642e4c45834d62b92b54b58.zip +1s
  gologin get emptyProfileFolder +1ms
  gologin emptyProfileFolder LENGTH :: 5984 +3ms
  gologin PROFILE LENGTH 5984 +4ms
  gologin Cleaning up.. /tmp/gologin_profile_6642e4c45834d62b92b54b58 +1ms
  gologin extactProfile /tmp/gologin_6642e4c45834d62b92b54b58.zip, /tmp/gologin_profile_6642e4c45834d62b92b54b58 +0ms
  gologin extraction done +36ms
  gologin reading /tmp/gologin_profile_6642e4c45834d62b92b54b58/Default/Preferences +0ms
  gologin Preferences file not exists waiting /tmp/gologin_profile_6642e4c45834d62b92b54b58/Default/Preferences . Using empty profile +0ms
  gologin get emptyProfileFolder +0ms
  gologin emptyProfileFolder LENGTH :: 5984 +1ms
  gologin extactProfile /tmp/gologin_6642e4c45834d62b92b54b58.zip, /tmp/gologin_profile_6642e4c45834d62b92b54b58 +0ms
node:internal/fs/promises:636
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open '/tmp/gologin_profile_6642e4c45834d62b92b54b58/Default/Preferences'
    at async open (node:internal/fs/promises:636:25)
    at async readFile (node:internal/fs/promises:1246:14)
    at async GoLogin.createStartup (file:///home/daniel/projects/ScraperService/node_modules/gologin/src/gologin.js:438:29)
    at async GoLogin.startLocal (file:///home/daniel/projects/ScraperService/node_modules/gologin/src/gologin.js:1385:5)
    at async file:///home/daniel/projects/ScraperService/gologin.js:33:17 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/gologin_profile_6642e4c45834d62b92b54b58/Default/Preferences'
}
```
/tmp/gologin_profile_6642e4c45834d62b92b54b58 looks like this:

![](https://i.imgur.com/bAlTDXB.png)

**Comment by danbopes** [comment]
Also, without `skipOrbitaHashChecking` this fails as well. I'd take a look into why that's failing as well.

**Comment by lisnake1412** [comment]
I get the same problem !, anyone who can fix this plz

**Comment by MartinCerny-awin** [comment]
We are having the same problem

**Comment by dropthemic** [comment]
For me, changing `gologin.js` method `emptyProfileFolder()` from:
`const currentDir = dirname(new URL(import.meta.url).pathname);`
to
`const currentDir = dirname(fileURLToPath(import.meta.url));`

fixed my issue.

**Comment by thatkit** [comment]
@NEITGNART thanks for the mentioning! I'll try to get to the fix as soon as I can

**Comment by tm4dev** [comment]
@danbopes @thatkit I think this was caused by zero_profile.zip, it contains subfolder `zero_profile`, after extraction the real path is /tmp/gologin_profile_6642e4c45834d62b92b54b58/zero_profile/Default/Preferences
Simply extract zero_profile.zip, recompress `Default folder + Last Version file`, not `zero_profile folder`, replace zero_profile.zip

**Comment by NephilimLord** [comment]
Fixed
