### ISSUE TITLE
Can't initiate a GoLogin instance on win due to wrong path ' C:\C:\Users\'

### ISSUE THREAD

**Issue by hydevip** [gologinapp/gologin#136]
OS: Win Server 2019 standard
Node js v: 20.13.1
Gologin v: 2.0.30

Can't initiate a GoLogin instance on win due to wrong path ' C:\C:\Users\' in  `gologin.js file` line 248 `emptyProfileFolder` method 

```
(async () => {
    const {GoLogin} = await import('gologin');
  const GL = new GoLogin({
    profile_id: 'XXXX',
    token: 'XXXXx',
    args: ['--disable-background-timer-throttling', '--disable-backgrounding-occluded-windows', '--disable-renderer-backgrounding'],
  });

  const { status, wsUrl } = await GL.start().catch((e) => {
    console.trace(e);

    return { status: 'failure' };
  });
.....
})();
```

The `new GoLogin(...)` will throw this error: 

```
C:\Users\Administrator\Desktop\chrome-server>node test-orbita.js
currentDir ::  /C:/Users/Administrator/Desktop/chrome-server/node_modules/gologin/src
zeroProfilePath ::  \C:\Users\Administrator\Desktop\chrome-server\node_modules\gologin\zero_profile.zip
_resolve(zeroProfilePath) ::  C:\C:\Users\Administrator\Desktop\chrome-server\node_modules\gologin\zero_profile.zip
Trace: Error: ENOENT: no such file or directory, open 'C:\C:\Users\Administrator\Desktop\chrome-server\node_modules\gologin\zero_profile.zip'
    at async open (node:internal/fs/promises:636:25)
    at async readFile (node:internal/fs/promises:1246:14)
    at async GoLogin.emptyProfileFolder (file:///C:/Users/Administrator/Desktop/chrome-server/node_modules/gologin/src/gologin.js:256:21)
    at async GoLogin.createStartup (file:///C:/Users/Administrator/Desktop/chrome-server/node_modules/gologin/src/gologin.js:401:26)
    at async GoLogin.start (file:///C:/Users/Administrator/Desktop/chrome-server/node_modules/gologin/src/gologin.js:1379:5)
    at async C:\Users\Administrator\Desktop\chrome-server\test-orbita.js:11:29 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\C:\\Users\\Administrator\\Desktop\\chrome-server\\node_modules\\gologin\\zero_profile.zip'
}
    at C:\Users\Administrator\Desktop\chrome-server\test-orbita.js:12:13
    at async C:\Users\Administrator\Desktop\chrome-server\test-orbita.js:11:29
Invalid status

C:\Users\Administrator\Desktop\chrome-server>node -v
v20.13.1
```

It looks like the issue is in the gologin.js file line 248 `emptyProfileFolder` method 
<img width="1027" alt="image" src="https://github.com/gologinapp/gologin/assets/35841222/7a2f9d2e-1298-4708-92d5-b1d5301251c8">

**Comment by hydevip** [comment]
The issue you're encountering with the double C: in the path is likely due to the handling of URL paths and file paths in a cross-platform Node.js environment. Specifically, new URL(import.meta.url).pathname can produce paths prefixed with a forward slash, which can lead to incorrect path concatenations when used with functions like join from the path module.

Here's a breakdown of why this happens and how to fix it:

Why This Happens
URL Pathname: new URL(import.meta.url).pathname returns a pathname that starts with a / on Windows. For example, /C:/Users/... which is valid in URL contexts but not in file system paths.
Path Join: The path.join method expects clean file paths. When you join a path that starts with /C:/, it can result in \C:\... which then resolves incorrectly to C:\C:\....

**Comment by Arsh1219** [comment]
Is there any fix for this bug?

**Comment by SattyaP** [comment]
Has your problem been resolved?

**Comment by YoussofKhawaja** [comment]
You can resolve this issue by creating a new profile in the GoLogin application, running it once there to initialize, and then using this profile id within your application.

**Comment by NephilimLord** [comment]
2.1.13 fixed
