### ISSUE TITLE
why its working with HTTP Proxy, and wasnt work with SOSCKS5 Proxy?

### ISSUE THREAD

**Issue by playset** [gologinapp/gologin#30]
Proxy Error. Check it and try again.
Trace: Error: Timeout exceeded
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\bot\node_modules\gologin\gologin.js:530:16)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
    at file:///C:/Users/Administrator/Desktop/bot/index.js:156:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

when i trying to use HTTP Proxy its working
but when i try to use with SOCKS5 Proxy it's wasnt working

**Comment by NephilimLord** [comment]
What package version do you use? This issue was fixed in ~1.0.28

**Comment by playset** [comment]
добрый день
попробую на 1.0.28

**Comment by NephilimLord** [comment]
нет, 1.0.31 последняя версия. ее надо попробовать
