### ISSUE TITLE
unexpected token .

### ISSUE THREAD

**Issue by ejames17** [gologinapp/gologin#4]
When I try to run one of the examples i get an unexpected error

`node example-create-profile.js 
/Users/jamese/Projects/gologintest/gologin.js:81
    return fpResponse?.body || {};
                      ^

SyntaxError: Unexpected token .
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)`

node -v : 14.6.0
Platform: macOs Catalina osx

**Comment by ejames17** [comment]
I got this working on the latest node version 16.2.0

**Comment by perioh** [comment]
same error
how you solved it?
> I got this working on the latest node version 16.2.0
