### ISSUE TITLE
Ubuntu 20.04 LTS is not supported.

### ISSUE THREAD

**Issue by 39ff** [gologinapp/gologin#43]
https://github.com/gologinapp/gologin#example

DEBUG=gologin* node example.js
```
Orbita downloading [==================] 12/mps 139.19/139.22MB 100% 0.0s
Orbita downloading [==================] 12/mps 139.21/139.22MB 100% 0.0s
Orbita downloading [==================] 12/mps 139.22/139.22MB 100% 0.0s
Orbita downloading [==================] 23/mps 139.22/139.22MB 100% 0.0s

Download completed
Checking Orbita archive
Extracting Orbita
Orbita hash checking
Hashfile downloading completed
Trace: Error: Error in sum matching. Please run script again.
    at BrowserChecker.checkBrowserSum (/home/ubuntu/node_modules/gologin/browser-checker.js:256:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BrowserChecker.downloadBrowser (/home/ubuntu/node_modules/gologin/browser-checker.js:111:5)
    at async GoLogin.start (/home/ubuntu/node_modules/gologin/gologin.js:1063:6)
    at async /home/ubuntu/example.js:10:31
    at /home/ubuntu/example.js:11:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/ubuntu/example.js:10:31
Invalid status
```

**Comment by NephilimLord** [comment]
It is weird you've got 4 logs "Orbita downloading". Do you run same script in other terminal at the same time?

**Comment by boomber5** [comment]
> It is weird you've got 4 logs "Orbita downloading". Do you run same script in other terminal at the same time?



> It is weird you've got 4 logs "Orbita downloading". Do you run same script in other terminal at the same time?

i am also facing the same issue. can we run this in vps server?

**Comment by swherden** [comment]
Had the same problem. Diasable the checkum check with skipOrbitaHashChecking: true in constructor of GoLogin
