### ISSUE TITLE
SyntaxError: Unexpected token . in gologin.js

### ISSUE THREAD

**Issue by nickolas98** [gologinapp/gologin#45]
root@server1:~/farm# node example.js 
/root/farm/gologin.js:99
    return fpResponse?.body || {};
                      ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/farm/example.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by nickolas98** [comment]
it is resolved by updating node to latest version
