### ISSUE TITLE
I cannot close the browser when I use'--headless'

### ISSUE THREAD

**Issue by AllCute** [gologinapp/gologin#9]
### Code
```python
gl = GoLogin({
    'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGVkMDBiZWMwYWJiMDIyYjY3NGZlMjAiLCJ0eXBlIjoiZGV2Iiwiand0aWQiOiI2MGVkMDE2N2UwMDUwYjgwNmNmYmIwMmMifQ.2YvSKJcLRvEVQewxQklBV0iEdbI2X5RrmJ5DOlGD2z8',
    'tmpdir': 'D:\\runtime\\gologin',
    'extra_params': ['--disable-gpu', '--blink-settings=imagesEnabled=false', '--headless'],
    'profile_id': '60ed69e36118cdd70a96009b'
})
debugger_address = gl.start()
chrome_options = Options()
chrome_options.add_experimental_option("debuggerAddress", debugger_address)
driver = webdriver.Chrome(executable_path=chrome_driver_path, options=chrome_options)
driver.get('https://google.com')
print(driver.title)
time.sleep(5)
driver.close()
time.sleep(1)
driver.quit()
time.sleep(5)
gl.stop()
```

### Error
```log
[Errno 13] Permission denied: 'D:\\runtime\\gologin\\gologin_60efae4387032c2d77845c13\\Default\\Cache\\data_0'
Traceback (most recent call last):
  File "D:\Projects\Python\auto-posting\gl\gologin.py", line 131, in commitProfile
    self.zipdir(self.profile_path, zipf)
  File "D:\Projects\Python\auto-posting\gl\gologin.py", line 115, in zipdir
    ziph.write(path, path.replace(self.profile_path, ''))
  File "D:\DevelopTools\Python\lib\zipfile.py", line 1761, in write
    with open(filename, "rb") as src, self.open(zinfo, 'w') as dest:
PermissionError: [Errno 13] Permission denied: 'D:\\runtime\\gologin\\gologin_60efae4387032c2d77845c13\\Default\\Cache\\data_0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\Python\auto-posting\gl_test.py", line 81, in <module>
    gl.stop()
  File "D:\Projects\Python\auto-posting\gl\gologin.py", line 120, in stop
    self.commitProfile()
  File "D:\Projects\Python\auto-posting\gl\gologin.py", line 157, in commitProfile
    self.stop(self)
TypeError: stop() takes 1 positional argument but 2 were given

Process finished with exit code 1
```

**Comment by FeelsBadMan1** [comment]
This is a easy solution. you open the Files in rb (readbyte) and another file in w (write) these modes only allow the given action so other actions are forbidden. make sure you use append mode what allows you to read and write. just put a "a" or "a+" if it should create the file in case it not exists

**Comment by Mixolap** [comment]
Permission denied in zip fix, update gologin.py from repository
